version: '3.5'
services:
  bootstrap_sidechain:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap_sidechain
    hostname: test_sidechain_mining_node_for_wallet
    networks:
      - sidechain
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=666 --rpc --rpcaddr="0.0.0.0" js /root/mine.js'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/side/genesis.json:/root/files/genesis.json:ro
      - ./files/ks:/root/.ethereum/devchain/keystore:rw
      - /home/developer/eth-wallet/dag-sidechain/dag/:/root/.ethash/:rw
    environment:
      - NETSTATS_SERVER=netstats_sidechain
    ports:
      - 30333:30303
      - 30333:30303/udp
      - 8666:8545
  netstats_sidechain:
    build: eth-netstats
    restart: on-failure
    container_name: netstats_sidechain
    networks:
      - sidechain
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - 3334:3000
  proxy_sidechain:
    build: proxy
    container_name: proxy_sidechain
    environment:
      - TARGET_HOST=172.16.1.135
      - TARGET_PORT=8666
    ports:
      - 8546:8545
    networks:
      - sidechain
networks:
  sidechain:
    name: sidechain