version: '3.5'
services:
  bootstrap_livenet:
    build: monitored-geth-client
    restart: on-failure
    container_name: bootstrap_livenet
    hostname: test_live_mining_node
    networks:
      - livenet
    entrypoint: /root/start.sh
    command: '--datadir=~/.ethereum/devchain --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain="*" --networkid=665 --rpc --rpcaddr="0.0.0.0" js /root/mine.js'
    volumes:
      - ./files/password:/root/files/password:ro
      - ./files/live/genesis.json:/root/files/genesis.json:ro
      - ./files/ks:/root/.ethereum/devchain/keystore:rw
      - /Users/snm-devops/ethereum-docker-live/dag/:/root/.ethash/:rw
    environment:
      - NETSTATS_SERVER=netstats_livenet
    ports:
      - "30343:30303"
      - "30343:30303/udp"
      - "8555:8545"
  netstats_livenet:
    build: eth-netstats
    restart: on-failure
    container_name: netstats_livenet
    networks:
      - livenet
    environment:
      - WS_SECRET=eth-net-stats-secret
    ports:
      - "3333:3000"
  proxy_livenet:
    build: proxy
    container_name: proxy_livenet
    environment:
      - GETH_HOST=172.16.1.177
      - GETH_PORT=8555
    ports:
      - 8545:8545
    networks:
      - livenet
networks:
  livenet:
    name: livenet